image:
  file: .gitpod.Dockerfile

# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Terminal 1
    init: echo "This is Terminal 1"
    command: echo "Hello from terminal 1"
  - name: Terminal 2
    init: echo "This is terminal 2"
    command: echo "Hello from terminal 2"
  - name: db
    command: |
      mkdir -p /workspace/data
      mongod --dbpath /workspace/data    

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 3000
    onOpen: open-preview
  - port: 27017 # mongodb
    onOpen: ignore    

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true
    pullRequestsFromForks: true
    addCheck: false
    addComment: false
    addBadge: true

vscode:
 extensions:
   - ms-azuretools.vscode-docker
